name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup
        run: yarn install
      - name: Unit Tests
        run: yarn coverage
